// Generated by CoffeeScript 1.6.2
(function() {
  describe('CopyCopter', function() {
    describe('initializing', function() {
      beforeEach(function() {
        return this.options = {
          apiKey: 'key',
          host: 'example.com'
        };
      });
      it('throws an error if not created with an apiKey', function() {
        var _this = this;

        delete this.options.apiKey;
        return expect(function() {
          return new CopyCopter(_this.options);
        }).toThrow('please provide the apiKey');
      });
      it('sets the apiKey on the instance', function() {
        var copycopter;

        this.options.apiKey = 'apiKey';
        copycopter = new CopyCopter(this.options);
        return copycopter.apiKey === 'apiKey';
      });
      it('throws an error if not created with a host', function() {
        var _this = this;

        delete this.options.host;
        return expect(function() {
          return new CopyCopter(_this.options);
        }).toThrow('please provide the host');
      });
      return it('sets the host on the instance', function() {
        var copycopter;

        this.options.host = 'example.com';
        copycopter = new CopyCopter(this.options);
        return copycopter.host === 'example.com';
      });
    });
    return describe('translating', function() {
      beforeEach(function() {
        return this.copycopter = new CopyCopter({
          apiKey: 'key',
          host: 'example.com'
        });
      });
      return it('makes an ajax call to the correct url', function() {
        return this.copycopter.t('this', {
          defaultValue: 'that'
        });
      });
    });
  });

}).call(this);
