// Generated by CoffeeScript 1.6.2
(function() {
  var CopyCopter;

  CopyCopter = (function() {
    function CopyCopter(options) {
      var key, value;

      for (key in options) {
        value = options[key];
        this[key] = value;
      }
      if (this.apiKey == null) {
        throw 'please provide the apiKey';
      }
      if (this.host == null) {
        throw 'please provide the host';
      }
      this.translations = {};
      this.load();
    }

    CopyCopter.prototype.translate = function(key, options) {
      var defaultValue, msg;

      defaultValue = options.defaultValue;
      delete options.defaultValue;
      msg = this.lookup(key) || defaultValue;
      return this.interpolate(msg, options);
    };

    CopyCopter.prototype.lookup = function(key, scope) {
      var message, _i, _len;

      scope = ['en'].concat(key.split('.'));
      message = this.translations;
      for (_i = 0, _len = scope.length; _i < _len; _i++) {
        key = scope[_i];
        message = message[key] || {};
      }
      if (message.length) {
        return message;
      }
    };

    CopyCopter.prototype.interpolate = function(msg, scope) {
      var key, regex, value, _i, _len, _ref;

      for (key in scope) {
        value = scope[key];
        _ref = [new RegExp("(.*)%{" + key + "}(.*)"), new RegExp("(.*){{" + key + "}}(.*)")];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          regex = _ref[_i];
          if (regex.test(msg)) {
            msg = msg.replace(regex, "$1" + value + "$2");
          }
        }
      }
      return msg;
    };

    CopyCopter.prototype.url = function() {
      return "//" + this.host + "/api/v2/projects/" + this.apiKey + "/published_blurbs?format=hierarchy";
    };

    CopyCopter.prototype.load = function() {
      var request,
        _this = this;

      request = jQuery.ajax({
        url: this.url(),
        cache: true,
        dataType: 'jsonp'
      });
      request.always(function() {
        return _this.isLoaded = true;
      });
      return request.success(function(data) {
        return _this.translations = data;
      });
    };

    return CopyCopter;

  })();

  this.CopyCopter = CopyCopter;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = CopyCopter;
  }

}).call(this);
