// Generated by CoffeeScript 1.6.2
(function() {
  var CopyCopter;

  CopyCopter = (function() {
    var load;

    function CopyCopter(options) {
      var key, value;

      for (key in options) {
        value = options[key];
        this[key] = value;
      }
      if (this.apiKey == null) {
        throw 'please provide the apiKey';
      }
      if (this.host == null) {
        throw 'please provide the host';
      }
    }

    CopyCopter.prototype.t = function(key, options) {
      return load(key);
    };

    load = function() {
      return console.log('here');
    };

    return CopyCopter;

  })();

  this.CopyCopter = CopyCopter;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = CopyCopter;
  }

}).call(this);
